## Required Libraries

In [11]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Preprocessing of Data

### Preprocessing For Image Training


In [2]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


## Preprocessing For Image Validation

In [3]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [4]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [5]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[141.5  129.5  139.5 ]
   [131.75 119.75 129.75]
   [142.75 130.75 140.75]
   ...
   [131.75 119.75 131.75]
   [123.75 111.75 123.75]
   [151.   139.   151.  ]]

  [[147.   135.   145.  ]
   [138.25 126.25 136.25]
   [140.5  128.5  138.5 ]
   ...
   [137.   125.   137.  ]
   [127.5  115.5  127.5 ]
   [146.75 134.75 146.75]]

  [[145.5  133.5  143.5 ]
   [128.75 116.75 126.75]
   [136.75 124.75 134.75]
   ...
   [145.5  133.5  145.5 ]
   [141.   129.   141.  ]
   [140.75 128.75 140.75]]

  ...

  [[189.   186.   195.  ]
   [188.5  185.5  194.5 ]
   [199.   196.   205.  ]
   ...
   [189.25 186.25 197.25]
   [199.25 196.25 207.25]
   [194.75 191.75 202.75]]

  [[194.   191.   200.  ]
   [183.5  180.5  189.5 ]
   [189.   186.   195.  ]
   ...
   [198.75 195.75 206.75]
   [198.   195.   206.  ]
   [200.5  197.5  208.5 ]]

  [[189.25 186.25 195.25]
   [194.   191.   200.  ]
   [193.5  190.5  199.5 ]
   ...
   [200.25 197.25 208.25]
   [204.75 201.75 212.75]
   [203.25 200.25 21

## Model Building

In [6]:
from tensorflow.keras.layers import Input,Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [7]:
model= tf.keras.models.Sequential()

In [8]:
# Define the input layer separately
model.add(Input(shape=(128, 128, 3)))

## Building Of Convolutional Layers

In [9]:
model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [10]:
model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [11]:
model.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [12]:
model.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [13]:
model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=512, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [14]:
# Add Flatten layer here to make the output 1-dimensional
model.add(Flatten())

In [15]:
model.add(tf.keras.layers.Dropout(0.25)) # To avoid overfitting

In [16]:
model.add(tf.keras.layers.Dense(units=1500,activation='relu'))

In [17]:
model.add(tf.keras.layers.Dropout(0.4))

In [18]:
## Output Layer
model.add(tf.keras.layers.Dense(units=38,activation='softmax'))

## Model Compiling

In [19]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

## Training Of Model

In [22]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1488s 673ms/step - accuracy: 0.3942 - loss: 2.1445 - val_accuracy: 0.8331 - val_loss: 0.5082
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1489s 678ms/step - accuracy: 0.8274 - loss: 0.5421 - val_accuracy: 0.9113 - val_loss: 0.2682
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1690s 769ms/step - accuracy: 0.9020 - loss: 0.3025 - val_accuracy: 0.9252 - val_loss: 0.2263
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1718s 782ms/step - accuracy: 0.9341 - loss: 0.2031 - val_accuracy: 0.9412 - val_loss: 0.1773
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1582s 720ms/step - accuracy: 0.9487 - loss: 0.1573 - val_accuracy: 0.9487 - val_loss: 0.1621
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1574s 717ms/step - accuracy: 0.9603 - loss: 0.1173 - val_accuracy: 0.9566 - val_loss: 0.1373
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1531s 697ms/step - accuracy: 0.9694 - loss: 0.0951 - val_accuracy: 0.9483 - val_loss: 0.1652
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1454s 662ms/s

## Evaluation of Model

In [23]:
#Model Evaluation on training set
train_loss,train_acc = model.evaluate(training_set)

2197/2197 ━━━━━━━━━━━━━━━━━━━━ 372s 170ms/step - accuracy: 0.9738 - loss: 0.0793


In [24]:
print(train_loss,train_acc)

0.07346925139427185 0.9758161902427673


## Saving The Model

In [25]:
#Model validation set
val_loss,val_acc = model.evaluate(validation_set)

550/550 ━━━━━━━━━━━━━━━━━━━━ 93s 170ms/step - accuracy: 0.9432 - loss: 0.2034


In [27]:
print(val_loss,val_acc)

0.19232192635536194 0.9470179677009583


In [29]:
model.save("trained_model.keras")

In [ ]:
training_history.history

## Saving History In json

In [ ]:
import json
with open("training_hist.json","w") as f:
    json.dump(training_history.history,f)

## Accuracy Visualization

In [ ]:
epochs  = [i for i in range(1,11)]
epochs

In [ ]:
training_history.history['accuracy']

In [ ]:
training_history.history['val_accuracy']

In [ ]:
epochs  = [i for i in range(1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlable("NO. of Epochs")
plt.ylable("Accuracy Result")
plt.xlable("Visualization of Accuracy Result")
plt.legend()
plt.show()